language: julia
os:
  - linux
  - osx
  - freebsd
julia:
  # - 1.0  # Latest LTS release (currently unsupported)
  - 1    # Latest stable release
  - nightly
notifications:
  email: false
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
